name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false
          persist-credentials: true
          token: ${{ secrets.FINE_GRAINED_PAT }}

      - name: Clone repository to target directory
        env:
          REPO_URL: "https://github.com/example/repo.git" # Ganti dengan URL repo yang ingin dikloning
          TARGET_DIR: "./plugins" # Ganti dengan direktori target
        run: |
          git clone "$REPO_URL" "$TARGET_DIR"
          mv "$TARGET_DIR"/* "$TARGET_DIR"/.* ../ || true
          rm -rf "$TARGET_DIR"

      - name: Commit and push changes
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git reset -- logs/
          
          if ! git commit -m "Auto commit after cloning repository [no ci]"; then
              echo "No changes to commit or commit failed"
              exit 0
          fi
          
          for i in {1..3}; do
              if git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:main --force; then
                  echo "Push successful on attempt $i"
                  exit 0
              else
                  echo "Push failed on attempt $i, retrying..."
                  git pull --rebase
              fi
          done
          
          echo "Failed to push after 3 attempts"
          exit 1
