name: Revert Commit

on:
  workflow_dispatch:

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Revert merge commit
        run: |
          git revert -m 1 ee3aba655561cb1e9d8984a1019b7aa8402bcd38
          git push origin HEAD
